FILE = cache-sim.c
default: run
run: cache-sim
	./cache-sim
gdb: cache-sim
	gdb ./cache-sim
chache-sim: cache-sim.c
	gcc -g -O0 -o cache-sim cache-sim.c
emacs: cache-sim.c
	emacs ./cache-sim.c
vi: cache-sim.c
	vi ./cache-sim.c

